spring:
  datasource:
    hikari:
      username: postgres
      password: pass
      maximum-pool-size: 50
      minimum-idle: 20
      connection-timeout: 20500
    url: jdbc:postgresql://file-postgres:5432/postgres
  liquibase:
    default-schema: public
    drop-first: true
    enabled: true
  http:
    encoding:
      charset: UTF-8
  activemq:
    packages:
      trust-all: false
      trusted: tr.com.tkeskin
logging:
  level:
    root: info
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream