server:
  port: 7007
  tomcat:
    max-threads: 500
    min-spare-threads: 50

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource

  jpa:
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect # bunu kald覺r覺rsan覺z select sorgular覺 patlar.
    properties:
      hibernate:
        cache:
          use_second_level_cache: true
          use_query_cache: true
          region:
            factory_class: org.hibernate.cache.jcache.JCacheRegionFactory
        hibernate:
          javax:
            cache:
              provider: com.hazelcast.cache.HazelcastCachingProvider
        default_schema: aa_file_transfer
        jdbc:
          lob:
            non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
springdoc:
  swagger-ui:
    path: /aa-fit-doc.html