spring:
  application:
    name: aa-file-transfer
  datasource:
    hikari:
      username: postgres
      password: MYPASSWD
      maximum-pool-size: 50
      minimum-idle: 20
      connection-timeout: 20500
    url: jdbc:postgresql://localhost:5432/postgres
  liquibase:
    default-schema: aa_file_transfer
    drop-first: false
    enabled: true
  http:
    encoding:
      charset: UTF-8
  activemq:
    broker-url: tcp://localhost:61616?jms.messagePrioritySupported=true
    packages:
      trust-all: false
      trusted: tr.com.aa
logging:
  level:
    root: info
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
springdoc:
  swagger-ui:
    path: /aa-fit-doc.html