spring:
  application:
    name: aa-file-transfer
  datasource:
    hikari:
      username: postgres
      password: MYPASSWD
      maximum-pool-size: 50
      minimum-idle: 20
    url: jdbc:postgresql://localhost:5432/postgres
  jpa:
    show-sql: true
  liquibase:
    default-schema: AA_FILE_TRANSFER
    enabled: false
logging.pattern.console:
logging:
  file:
    max-size: 50MB
    name: /logs/aa-file-transfer/app.log
  level:
    ROOT: ERROR
    tr.com: INFO
