spring:
  application:
    name: file-transfer
  datasource:
    hikari:
      username: postgres
      password: pass
      maximum-pool-size: 50
      minimum-idle: 20
      connection-timeout: 20500
    url: jdbc:postgresql://localhost:5432/postgres
  liquibase:
    default-schema: file_transfer
    drop-first: true
    enabled: true
  http:
    encoding:
      charset: UTF-8
  activemq:
    broker-url: tcp://localhost:61616?jms.messagePrioritySupported=true
    packages:
      trust-all: false
      trusted: tr.com.tkeskin
logging:
  level:
    root: info
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream